services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:15
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
